version: '3'
services:
  elk:
    container_name: elk_container
    image: sebp/elk:661
    ports:
      - "127.0.0.1:5601:5601"
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:5044:5044"
    volumes:
      - ./logs:/logs
      - ./logstash.conf:/etc/logstash/conf.d/30-output.conf
      - elkdata:/var/lib/elasticsearch
volumes:
  elkdata: {}
